name: release image
on:
  push:
    tags:
      - 'image-v*' # push events for tags matching image-v for version (image-v1.0, etc)
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Test image version to push'
        required: true
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:17}) # refs/tags/image-v1.0.0 substring starting at 1.0.0
        if: ${{github.event.inputs.test_version == ''}}
      - name: set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${{test_version}}-canary)
        if: ${{github.event.inputs.test_version != ''}}
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: './vmss-prototype'
          file: './Dockerfile'
          tags: |
            ghcr.io/jackfrancis/kamino:${{ env.RELEASE_VERSION }}
            ghcr.io/jackfrancis/kamino:latest
